#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 10 07:59:32 2017

@author: brendontucker
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

df = pd.read_json("/Users/brendontucker/Kaggle/RentHop/data/train.json")

ulimit = np.percentile(df.price.values, 99)

prices = df['price']

cnt_srs = df['bathrooms'].value_counts()
